stages:
  - sonar
  - test

variables:
  HOST: '192.168.101.132'

sonar:
  stage: sonar
  script:
    - echo "scanning sonar"
    - sonar-scanner -Dsonar.projectKey=eximbank-ui -Dsonar.sources=. -Dsonar.host.url=https://sonar.cyberspace.vn/ -Dsonar.login=sqp_51b2de09b4acb6c7fd019fb238f4c7d1fcad2e91
  only:
    - develop
  allow_failure: true
  tags:
    - sonar
    - develop

test:
  image: node:18
  stage: test
  script:
    - echo "---------------------------------------------test"
    - node --version
    - npm install -g pnpm
    - pnpm install -f
    - pnpm run test:coverage
  # only:
  #   - develop
  tags:
    - gitlab-runner-02
  coverage: /All files(?:[^|]*\|){4}\s*(\S+)/
  artifacts:
    paths:
      - coverage/
