#!/bin/sh

# Check if a file was provided
if [ -z "$1" ]; then
  echo "Error: No commit message file provided."
  exit 1
fi

# Read the commit message from the file
commit_message=$(cat "$1")

# Check if the commit message starts with a valid prefix (case-insensitive)
if ! echo "$commit_message" | grep -qE '^(feat|fix|perf|style|refactor|revert|test|docs|chore|workflow|ci|types|wip): '; then
  echo "Error: Commit message must start with one of the following prefixes (case-insensitive): (feat|fix|perf|style|refactor|revert|test|docs|chore|workflow|ci|types|wip): "
  exit 1
fi

echo "The commit message is valid."
