#!/bin/sh
echo "Check branch before push"
branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" = "develop" ] || [ "$branch" = "main" ]; then
  echo "Cannot push directly to $branch branch. Please create branch and make a pull request."
  exit 1
fi
